### ISSUE TITLE
Missing Requirement for Install

### ISSUE THREAD

**Issue by cpjet64** [Solar-Helix-Independent-Transport/allianceauth-celeryanalytics#6]
When installing CeleryAnalytics you need to manually `pip install django-ninja` as it is not defined in the requirements.

Running initial migration for CeleryAnalytics without manually `pip install django-ninja` results in the following error:

```shell
Traceback (most recent call last):
  File "/home/allianceserver/myauth/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 91, in handle
    self.check(databases=[database])
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/allianceserver/myauth/myauth/urls.py", line 2, in <module>
    from allianceauth import urls
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/allianceauth/urls.py", line 12, in <module>
    import allianceauth.services.urls
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/allianceauth/services/urls.py", line 17, in <module>
    services = get_hooks('services_hook')
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/allianceauth/hooks.py", line 123, in get_hooks
    register_all_hooks()
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/allianceauth/hooks.py", line 112, in register_all_hooks
    hooks = list(get_app_submodules('auth_hooks'))
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/allianceauth/hooks.py", line 101, in get_app_submodules
    yield name, import_module(f'{name}.{module_name}')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/celeryanalytics/auth_hooks.py", line 1, in <module>
    from . import urls
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/celeryanalytics/urls.py", line 5, in <module>
    from .api import api
  File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/celeryanalytics/api.py", line 6, in <module>
    from ninja import Field, Form, NinjaAPI
ModuleNotFoundError: No module named 'ninja'
```

**Comment by pvyParts** [comment]
fixed in 0.0.6
